# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c689e90a52beaf18b524de0d87fb88d7271bccf453349193f1169c3aeb5d90ee5662778ed97b34bfc22385deba9fe462b64a050532cf6e47a61c3e3fa7f48fa2

test:
  secret_key_base: cdeb02c2f072fb547a9fa4dda6b3ca935d1156b8f936edc5f78b00a408ee756490cb619a84c1afe45d5c974234a86508d73e053603259f5cc68fe90ff94ea4ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
